//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view1
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> SLTon { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string TenDV { get; set; }
        public string Anh { get; set; }
        public Nullable<int> MaDV { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
    }
}
